### ISSUE TITLE
Use MIT license for project

### ISSUE THREAD

**Issue by investor55** [UBC-MDS/522_group_36#13]
Think something is wrong with the MIT license because Github is not recognizing it

![image](https://github.com/user-attachments/assets/66ed79fd-40a0-4e6b-a6fa-03f2e6290bd4)

**Comment by lixuanlinjam** [comment]
I think that's probably because we didn't check it when setting up the repo, and in the LICENSE.md I just simply copy pasted the MIT License. Anyone know how to make this work?

**Comment by investor55** [comment]
It appears that the issue arises because your LICENSE.md contains two different licenses:

A Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 (CC BY-NC-ND 4.0) license for the analysis report.
An MIT License for the software code.
GitHub's license recognition system may be failing to identify the LICENSE.md as a standard license because it doesn't expect a combined structure or multiple licenses in a single file.


Let's use only MIT license: Copy this to the license page @lixuanlinjam 


LICENSE
MIT License

Copyright (c) 2024 Master of Data Science at the University of British Columbia

Permission is hereby granted, free of charge, to any person obtaining a copy of this material, including the software, analysis report, and associated documentation files (collectively referred to as the "Material"), to deal in the Material without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Material, and to permit persons to whom the Material is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Material.

THE MATERIAL IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE MATERIAL OR THE USE OR OTHER DEALINGS IN THE MATERIAL.

**Comment by lixuanlinjam** [comment]
emmmm but we are asked to contain two different licenses

**Comment by investor55** [comment]
ok it's fine let's leave this
