### ISSUE TITLE
Add data validation method to README 

### ISSUE THREAD

**Issue by investor55** [UBC-MDS/522_group_36#23]
Since we have our data validation as a script, Daniel mentioned we should add how to run it into the README

**Comment by investor55** [comment]
Here's a suggested addition:

Data Validation
To run the data validation script, use the following command:
```
python path/to/your_script.py
```
Replace path/to/your_script.py with the actual path to the validation script. Make sure to provide any required arguments or additional setup steps if necessary.

**Comment by lixuanlinjam** [comment]
surely we should add this to the readme file! and I will also add the container part to the readme. can one of you add the data validation part? @YibinLong @jiayili7 @hanwang205

**Comment by investor55** [comment]
Sure, I can add it after data validation branch is merged. Any help needed on that @YibinLong

**Comment by YibinLong** [comment]
Nah, I got it!
