### ISSUE TITLE
readme issues

### ISSUE THREAD

**Issue by lixuanlinjam** [UBC-MDS/522_group_36#59]
wrong file name (should use "_"):
quarto render report/yellow-taxi-analysis.qmd --to html

**Comment by lixuanlinjam** [comment]
these commands style are not consistent:

python -m scripts.download_data 

python -m scripts.run_eda run-all data/processed/yellow_tripdata_2024-01_validated.csv \
--charts_dir charts

python scripts/modeling.py --x-train-path data/processed/X_train.csv --y-train-path data/processed/y_train.csv --x-test-path data/processed/X_test.csv --y-test-path data/processed/y_test.csv

**Comment by lixuanlinjam** [comment]
the order of these two commands are wrong in the instructions:

python -m scripts.run_validation
python -m scripts.download_data

**Comment by lixuanlinjam** [comment]
done

**Comment by investor55** [comment]
@lixuanlinjam 

Can we modify the read me option 2. A user should clone, build using docker compose up, then run make all in the container Terminal. I'm adding make to the container in https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/pull/73

**Comment by lixuanlinjam** [comment]
> @lixuanlinjam
> 
> Can we modify the read me option 2. A user should clone, build using docker compose up, then run make all in the container Terminal. I'm adding make to the container in #73

yup! you can directly edit it regarding the new changes and make instructions accordingly. @jiayili7
