### ISSUE TITLE
Improve organization

### ISSUE THREAD

**Issue by investor55** [UBC-MDS/522_group_36#67]
- Make sure file structure not confusing
- Make validation folder more clearer (make sure still works, change import location)
-

**Comment by YibinLong** [comment]
woops I did some of this in #69 - I just moved schema_postEDA into validation folder

we still have to look through our structure more thoroughly to make sure we got everything

**Comment by YibinLong** [comment]
Make sure our organization at least resemble's tiff's at https://github.com/ttimbers/breast_cancer_predictor_py?tab=readme-ov-file

**Comment by YibinLong** [comment]
Everything looks good in terms of organization, except do we need this:
https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/blob/main/data/yellow_tripdata_2024-01.csv
- we already have processed and raw data folders @jiayili7

**Comment by investor55** [comment]
https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/pull/82

**Comment by investor55** [comment]
@YibinLong  Won't delete because it's being referenced by some files that needs a careful look through. Will pass this one 

The following files in the repository reference data/yellow_tripdata_2024-01.csv directly:

report/yellow_taxi_analysis.ipynb

[View file](https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/blob/e88f6be934d9e589cc315a8238f294bc8caf23cb/report/yellow_taxi_analysis.ipynb#L100-L174)
scripts/run_validation.py

[View file](https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/blob/e88f6be934d9e589cc315a8238f294bc8caf23cb/scripts/run_validation.py#L36-L104)
config/validation_config.yaml

[View file](https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/blob/e88f6be934d9e589cc315a8238f294bc8caf23cb/config/validation_config.yaml#L1-L25)
report/1c022a3c875c1a63/yellow_taxi_analysis.html

[View file](https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/blob/e88f6be934d9e589cc315a8238f294bc8caf23cb/report/1c022a3c875c1a63/yellow_taxi_analysis.html#L127-L141)
report/yellow_taxi_analysis.qmd

[View file](https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/blob/e88f6be934d9e589cc315a8238f294bc8caf23cb/report/yellow_taxi_analysis.qmd#L31-L65)
report/1c022a3c875c1a63/index.html

[View file](https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/blob/e88f6be934d9e589cc315a8238f294bc8caf23cb/report/1c022a3c875c1a63/index.html#L123-L139)
