### ISSUE TITLE
Docstirng for modeling.py

### ISSUE THREAD

**Issue by investor55** [UBC-MDS/522_group_36#84]
Can we add some docstring to the modeling py 

https://github.com/UBC-MDS/DSCI_522_Group36_taxi_fare_predictor/blob/main/scripts/modeling.py

From Julian:
In the modelling.py script, you could add a more detailed docstring explaining what the function is doing to make it more understandable for the reader.

https://github.com/UBC-MDS/data-analysis-review-2024/issues/16

**Comment by YibinLong** [comment]
done in #85
